// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace New_folder_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241205185022_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.1.24081.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.BOM", b =>
                {
                    b.Property<string>("ParentPart")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChildPart")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OpNo")
                        .HasColumnType("int");

                    b.Property<decimal>("RequiredQuantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ParentPart", "ChildPart");

                    b.ToTable("BOMs");
                });

            modelBuilder.Entity("Backend.Models.Demand", b =>
                {
                    b.Property<string>("DemandNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DemandDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("DemandNo");

                    b.ToTable("Demands");
                });

            modelBuilder.Entity("Backend.Models.Supply", b =>
                {
                    b.Property<string>("SupplyNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("SupplyDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SupplyNo");

                    b.ToTable("Supplies");
                });

            modelBuilder.Entity("Backend.Models.WorkOrder", b =>
                {
                    b.Property<string>("WorkOrderNo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompletedQty")
                        .HasColumnType("int");

                    b.Property<string>("MachineNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderQty")
                        .HasColumnType("int");

                    b.HasKey("WorkOrderNo");

                    b.ToTable("WorkOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
